version: "3.9"
services:
  # Servidor web
  application:
    image: ubuntu/node
    container_name: app-node
    command: npx nodemon /app/index.js --legacy-watch
    ports:
      - 80:80
    environment:
      - PORT=80
      - DB_HOST=database
      - DB_SCHEMA=login
      - DB_USER=root
      - DB_PASSWORD=toor
    volumes:
      - .:/app
      - /app/node_modules
  
  # Base de datos
  database:
    image: mysql
    container_name: app-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=login
    volumes:
      - db-mysql:/var/lib/mysql

volumes:
  db-mysql:
    external: true